// source: proto/orderbook_socket/v1/orderbook.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.orderbook_socket.v1.Orderbook', null, global);
goog.exportSymbol('proto.orderbook_socket.v1.OrderbookItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.orderbook_socket.v1.Orderbook = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.orderbook_socket.v1.Orderbook.repeatedFields_, null);
};
goog.inherits(proto.orderbook_socket.v1.Orderbook, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.orderbook_socket.v1.Orderbook.displayName = 'proto.orderbook_socket.v1.Orderbook';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.orderbook_socket.v1.OrderbookItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.orderbook_socket.v1.OrderbookItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.orderbook_socket.v1.OrderbookItem.displayName = 'proto.orderbook_socket.v1.OrderbookItem';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.orderbook_socket.v1.Orderbook.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.orderbook_socket.v1.Orderbook.prototype.toObject = function(opt_includeInstance) {
  return proto.orderbook_socket.v1.Orderbook.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.orderbook_socket.v1.Orderbook} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orderbook_socket.v1.Orderbook.toObject = function(includeInstance, msg) {
  var f, obj = {
    pair: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bidsList: jspb.Message.toObjectList(msg.getBidsList(),
    proto.orderbook_socket.v1.OrderbookItem.toObject, includeInstance),
    asksList: jspb.Message.toObjectList(msg.getAsksList(),
    proto.orderbook_socket.v1.OrderbookItem.toObject, includeInstance),
    twentyFourHourVolume: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    twentyFourHourLow: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    twentyFourHourHigh: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    twentyFourHourChange: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    lastTradePrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    spread: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    twentyFourHourPercentChange: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    twentyFourHourPricePercentChange: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.orderbook_socket.v1.Orderbook}
 */
proto.orderbook_socket.v1.Orderbook.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.orderbook_socket.v1.Orderbook;
  return proto.orderbook_socket.v1.Orderbook.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.orderbook_socket.v1.Orderbook} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.orderbook_socket.v1.Orderbook}
 */
proto.orderbook_socket.v1.Orderbook.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPair(value);
      break;
    case 2:
      var value = new proto.orderbook_socket.v1.OrderbookItem;
      reader.readMessage(value,proto.orderbook_socket.v1.OrderbookItem.deserializeBinaryFromReader);
      msg.addBids(value);
      break;
    case 3:
      var value = new proto.orderbook_socket.v1.OrderbookItem;
      reader.readMessage(value,proto.orderbook_socket.v1.OrderbookItem.deserializeBinaryFromReader);
      msg.addAsks(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourVolume(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourLow(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourHigh(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourChange(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLastTradePrice(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSpread(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourPercentChange(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTwentyFourHourPricePercentChange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.orderbook_socket.v1.Orderbook.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.orderbook_socket.v1.Orderbook.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.orderbook_socket.v1.Orderbook} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orderbook_socket.v1.Orderbook.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPair();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.orderbook_socket.v1.OrderbookItem.serializeBinaryToWriter
    );
  }
  f = message.getAsksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.orderbook_socket.v1.OrderbookItem.serializeBinaryToWriter
    );
  }
  f = message.getTwentyFourHourVolume();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getTwentyFourHourLow();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTwentyFourHourHigh();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getTwentyFourHourChange();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getLastTradePrice();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getSpread();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getTwentyFourHourPercentChange();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getTwentyFourHourPricePercentChange();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
};


/**
 * optional string pair = 1;
 * @return {string}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getPair = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setPair = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated OrderbookItem bids = 2;
 * @return {!Array<!proto.orderbook_socket.v1.OrderbookItem>}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getBidsList = function() {
  return /** @type{!Array<!proto.orderbook_socket.v1.OrderbookItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.orderbook_socket.v1.OrderbookItem, 2));
};


/**
 * @param {!Array<!proto.orderbook_socket.v1.OrderbookItem>} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
*/
proto.orderbook_socket.v1.Orderbook.prototype.setBidsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.orderbook_socket.v1.OrderbookItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.orderbook_socket.v1.OrderbookItem}
 */
proto.orderbook_socket.v1.Orderbook.prototype.addBids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.orderbook_socket.v1.OrderbookItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.clearBidsList = function() {
  return this.setBidsList([]);
};


/**
 * repeated OrderbookItem asks = 3;
 * @return {!Array<!proto.orderbook_socket.v1.OrderbookItem>}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getAsksList = function() {
  return /** @type{!Array<!proto.orderbook_socket.v1.OrderbookItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.orderbook_socket.v1.OrderbookItem, 3));
};


/**
 * @param {!Array<!proto.orderbook_socket.v1.OrderbookItem>} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
*/
proto.orderbook_socket.v1.Orderbook.prototype.setAsksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.orderbook_socket.v1.OrderbookItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.orderbook_socket.v1.OrderbookItem}
 */
proto.orderbook_socket.v1.Orderbook.prototype.addAsks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.orderbook_socket.v1.OrderbookItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.clearAsksList = function() {
  return this.setAsksList([]);
};


/**
 * optional double twenty_four_hour_volume = 4;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourVolume = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourVolume = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double twenty_four_hour_low = 5;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourLow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourLow = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double twenty_four_hour_high = 6;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourHigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourHigh = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double twenty_four_hour_change = 7;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double last_trade_price = 8;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getLastTradePrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setLastTradePrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double spread = 9;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getSpread = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setSpread = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double twenty_four_hour_percent_change = 10;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourPercentChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourPercentChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double twenty_four_hour_price_percent_change = 11;
 * @return {number}
 */
proto.orderbook_socket.v1.Orderbook.prototype.getTwentyFourHourPricePercentChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.Orderbook} returns this
 */
proto.orderbook_socket.v1.Orderbook.prototype.setTwentyFourHourPricePercentChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.toObject = function(opt_includeInstance) {
  return proto.orderbook_socket.v1.OrderbookItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.orderbook_socket.v1.OrderbookItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orderbook_socket.v1.OrderbookItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    quantity: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.orderbook_socket.v1.OrderbookItem}
 */
proto.orderbook_socket.v1.OrderbookItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.orderbook_socket.v1.OrderbookItem;
  return proto.orderbook_socket.v1.OrderbookItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.orderbook_socket.v1.OrderbookItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.orderbook_socket.v1.OrderbookItem}
 */
proto.orderbook_socket.v1.OrderbookItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.orderbook_socket.v1.OrderbookItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.orderbook_socket.v1.OrderbookItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orderbook_socket.v1.OrderbookItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional double price = 1;
 * @return {number}
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.OrderbookItem} returns this
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double quantity = 2;
 * @return {number}
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.orderbook_socket.v1.OrderbookItem} returns this
 */
proto.orderbook_socket.v1.OrderbookItem.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


goog.object.extend(exports, proto.orderbook_socket.v1);
